services:
  ecourse:
    container_name: ecourse
    build:
      context: .                     
      dockerfile: Dockerfile
      args:
        VITE_PROD_PB_URL: "http://localhost:8090"   # <-- Change it for your IP
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ecourse:/app/pb/pb_data

volumes:
  ecourse:
